### ISSUE TITLE
Run this application without docker.

### ISSUE THREAD

**Issue by waghts95** [ash2shukla/streamlit-stream#2]
Hi, thank you very much for your amazing work.
Please let me know how can I run this application without docker.

**Comment by waghts95** [comment]
I have tried,
In consume/src,
streamlit run main.py

In producer,
uvicorn main:app --reload

But getting error, error screenshot
![error](https://user-images.githubusercontent.com/20351285/118362236-5b8e8000-b5ac-11eb-9324-61c3b0d0f941.JPG)
 file is attached below.

**Comment by ash2shukla** [comment]
It is coming because there's no websocket server running at wsserver host,

Run this command in producers directory,
uvicorn main:app --host 0.0.0.0 --port 8080

Then in consumer/utils.py change to WS_CONN = "ws://localhost:8080/"

It should work then.

**Comment by waghts95** [comment]
Thank you.
Worked.
